channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.8
  - pip=21.0.1
  - wheel=0.36.2
  - openssl=1.1.1k
  - sqlite=3.35.4
  - setuptools=52.0.0
  - ca-certificates=2021.4.13
  - numpy=1.20.2
  - pillow=8.2.0
  - scipy=1.6.3
  - scikit-learn=0.24.2
  - plyfile=0.7.2
  - joblib=1.0.1
  - polyscope=0.1.6
  - tqdm=4.54.1
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pip:
    - potpourri3d==0.0.3
    - robust-laplacian==0.2.4